module.exports = {
  collectCoverageFrom: [
    '**/*.{js,jsx,ts,tsx}',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/.next/**',
    '!**/coverage/**',
    '!**/eslint/**',
    '!**/eslintrc/**',
    '!**/config/**',
    '!**/config/js',
    '!jest/config/**',
  ],
  testEnvironment: 'jsdom',
  testPathIgnorePatterns: ['/node_modules/', '/.next/'],
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': '<rootDir>/node_modules/babel-jest',
  },
  transformIgnorePatterns: [
    '/node_modules/',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
  moduleNameMapper: {
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
    '^@atoms$': '<rootDir>/components/atoms/index.ts',
    '^@atoms/*$': '<rootDir>/components/atoms/*',
    '^@components$': '<rootDir>/components/index.ts',
    '^@components/*$': '<rootDir>/components/*',
    '^@hooks$': '<rootDir>/hooks/index.ts',
    '^@hooks/*$': '<rootDir>/hooks/*',
    '^@icons$': '<rootDir>/icons/index.ts',
    '^@icons/searchEye/searchEye$': '<rootDir>/icons/searchEye/searchEye',
    '^@icons/close/close$': '<rootDir>/icons/close/close',
    '^@interfaces$': '<rootDir>/interfaces/index.ts',
    '^@interfaces/*$': '<rootDir>/interfaces/*',
    '^@molecules$': '<rootDir>/components/molecules/index.ts',
    '^@molecules/*$': '<rootDir>/components/molecules/*',
    '^@organisms$': '<rootDir>/components/organisms/index.ts',
    '^@organisms/*$': '<rootDir>/components/organisms/*',
    '^@redux$': '<rootDir>/redux/index.ts',
    '^@redux/animes/actions$': '<rootDir>/redux/animes/actions',
    '^@services$': '<rootDir>/services/index.ts',
    '^@services/animes$': '<rootDir>/services/animes',
    '^@theme$': '<rootDir>/theme/index.ts',
    '^@theme/*$': '<rootDir>/theme/*',
  },
};
