export const FETCH_ANIMES = 'FETCH_ANIMES';
export const SUCCESS_FETCH_ANIMES_DATA = 'SUCCESS_FETCH_ANIMES_DATA';
export const SUCCESS_FETCH_ANIMES_PAGINATION = 'SUCCESS_FETCH_ANIMES_PAGINATION';
export const SUCCESS_FETCH_ANIMES_LINKS = 'SUCCESS_FETCH_ANIMES_LINKS';
